apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: cloudpak-grafana
  namespace: cloudpak-monitoring
spec:
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: Passw0rd!
      admin_user: root
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
